#+title: Emacs Configuration
#+author: Ben Domine
#+property: header-args:emacs-lisp :tangle yes :results silent
#+startup: overview

* Early Initialization
** Config File Shortcut
Because of how frequently I visit this file, I want a function to quickly find it. I want this to be the very first thing I do, so that if something breaks this function still ends up loading whenever possible.
#+begin_src emacs-lisp
  (defun config ()
      "Find the config file."
      (interactive)
      (find-file "~/.emacs.d/config.org"))
#+end_src

** Other Config Files
Store customize code in a different file:
#+begin_src emacs-lisp
  (setq custom-file "~/.emacs.d/custom.el")
  (load custom-file 'noerror)
#+end_src

Packages I’m currently developing will be in different files; load them also:
#+begin_src emacs-lisp
  (load "~/.emacs.d/my-project-manager.el")
  (load "~/.emacs.d/my-delete.el")
#+end_src
** Basic GUI Tweaks
First GUI customizations. We want fullscreen, no tool bar, and a dark frame:
#+begin_src emacs-lisp
  (tool-bar-mode -1)
  (add-to-list 'default-frame-alist '(fullscreen . maximized))
  (set-frame-parameter nil 'ns-appearance 'dark)
#+end_src

** Package Management
We’ll be using use-package. Much of this code comes from [[https://www.shaneikennedy.xyz/blog/emacs-intro][this blog post]] by Shane Kennedy.
First, a macro for appending to a list:
#+begin_src emacs-lisp
  (defmacro append-to-list (target suffix)
      "Append SUFFIX to TARGET in place."
      `(setq ,target (append ,target ,suffix)))
#+end_src

Next, we’ll update our package archives:
#+begin_src emacs-lisp
  (require 'package)

  (append-to-list package-archives
      '(("melpa" . "http://melpa.org/packages/")
           ("melpa-stable" . "http://stable.melpa.org/packages/")
           ("org-elpa" . "https://orgmode.org/elpa/")))
#+end_src

And load from our package list:
#+begin_src emacs-lisp
  (package-initialize)
#+end_src

Now we’ll set up use-package. We need to refresh the package archive so we can get the latest packages, and install use-package.
#+begin_src emacs-lisp
  (unless (package-installed-p 'use-package)
      (package-refresh-contents)
      (package-install 'use-package))
#+end_src

Finally, some settings for use-pacakge. We want to make ensure the default, which causes use-package to download stuff if it’s not installed. We also want to turn on verbose installation, so that we get error logging when something breaks.
#+begin_src emacs-lisp
  (setq
      use-package-always-ensure t
      use-package-verbose t)
#+end_src
* Keybindings
** Mac Rebinding
I primarily use Mac, so I want most keybindings to use the command key. So, I’ll switch the command and control keys.
#+begin_src emacs-lisp
  (setq mac-command-modifier 'control)
  (setq mac-control-modifier 'super)
#+end_src

This means that I need to resolve the keyboard conflicts that arise from mac taking over certain commands, such as command + space.
#+begin_src emacs-lisp :tangle no
  (global-set-key (kbd "C-o") 'set-mark-command)
#+end_src
** Undo, Redo
I want to use C-/ for commenting, so I’ll bind undo to C-z like normal. I don’t need to use suspend-frame much at all, so this should be acceptable.
#+begin_src emacs-lisp :tangle no
  (global-set-key (kbd "C-z") 'undo)
  (global-set-key (kbd "C-S-z") 'undo-redo)
#+end_src
** S-Expressions
The built-in keybindings for forward- and backward-sexp are prefixed with C-M-. I just generally dislike this combination.

#+begin_src emacs-lisp
  (global-set-key (kbd "M-F") 'forward-sexp)
  (global-set-key (kbd "M-B") 'backward-sexp)
#+end_src

* UI
** Scrolling
I want precision pixel scrolling, meaning that when I use the scroll wheel I want smooth scrolling instead of line-by-line scrolling. This obviously only has an impact in GUI mode. Also, it can cause lag depending on the machine and version/port of emacs!
#+begin_src emacs-lisp
  (pixel-scroll-precision-mode)
#+end_src

** Icons
I’m using nerd-icons for doom-modeline and other icon-requiring packages.
#+begin_src emacs-lisp
  (use-package nerd-icons
      :custom
      (nerd-icons-font-family "Symbols Nerd Font Mono")
      )
#+end_src

Note: if this doesn’t work on a new computer, run nerd-icons-install-fonts.

** Themes
I’ll use doom-themes because of its broad selection. Screenshots of some of these themes can be found [[https://github.com/doomemacs/themes/tree/screenshots][here]].

This is a short list of themes I like:
:themes:
- Doom-one (boring but classic)
- doom-city-lights
- Doom-oceanic-next
- doom-dark+
- Doom-solarized-dark (maybe)
- Doom-outrun-electric (probably not, it looks cool as hell though)
- Doom-snazzy (pretty basic but nice contrast)
- Doom-dracula (I really like this one actually)
:END:
For now I’ll just go with dark+.
#+begin_src emacs-lisp :results silent
  (use-package doom-themes
      :init
      (load-theme 'doom-dracula))
#+end_src

I want the active line number in line number mode to be highlighted more brightly:
#+begin_src emacs-lisp
  (set-face-attribute 'line-number-current-line nil
      :foreground (face-attribute 'highlight :background))
#+end_src

** Modeline
I’m using doom-modeline. The customization options can be found at [[https://github.com/seagle0128/doom-modeline][the github repo]].
#+begin_src emacs-lisp
  (use-package doom-modeline
      :ensure t
      :init (doom-modeline-mode 1))
#+end_src

I’ve had some issues with lag in the past, and I heard that this was supposed to help:
#+begin_src emacs-lisp
  (setq inhibit-compacting-font-caches t)
#+end_src

Let’s take advantage of the icons we’ve added and force doom-modeline to use them. This should be on by default but it can’t hurt.
#+begin_src emacs-lisp
  (setq doom-modeline-icon t)
#+end_src

I also want to see the time, but not the system load average:
#+begin_src emacs-lisp
  (setq display-time-default-load-average nil)
  (setq doom-modeline-time-icon t)
  (setq doom-modeline-time t)
  (display-time)
#+end_src

Just for fun, I’ll also enable the battery indicator, updating every 30 seconds:
#+begin_src emacs-lisp
  (setq battery-update-interval 30)
  (setq doom-modeline-battery t)
  (display-battery-mode +1)
#+end_src

** Tab Bar
I want to move away from centaur-tabs, as it’s a very buggy and generally annoying package. Instead, I’ll customize the built-in tab bar to work a little better.
#+begin_src emacs-lisp
  ;; (let ((color (face-attribute 'highlight :background)))
  ;; 	(set-face-attribute 'tab-bar-tab nil :box '(:line-width 10 :style flat-button) :underline `(:color ,color :style line :position t)
  ;; 	))
  (defun my-setup-tab-bar-faces ()
    "Apply GUI-specific faces for the tab bar."
    ;; Optional: Ensure we are in a GUI before setting GUI attributes
    (when (display-graphic-p)
      (let ((color (face-attribute 'highlight :background nil t)))
        ;; Only apply if a valid color was actually returned
        (when (and color (not (eq color 'unspecified)))
          (set-face-attribute 'tab-bar-tab nil 
                              :box '(:line-width 10 :style flat-button) 
                              :underline `(:color ,color :style line :position t))))))

  ;; If starting as a daemon, wait for the frame. 
  ;; If starting normally (standalone app), run it immediately.
  (if (daemonp)
      (add-hook 'server-after-make-frame-hook #'my-setup-tab-bar-faces)
    (my-setup-tab-bar-faces))
#+end_src

The above face adds an underline, but the box face messes with the underline on the close button for some reason. SETUP TAB BAR: replace the file path below with the file path found in ~tab-bar-close-button~ without any customization.

#+begin_src emacs-lisp
  (add-hook 'tab-bar-mode-hook (lambda () (setq tab-bar-close-button
  	#(" " 0 1
  	 (close-tab t rear-nonsticky t help-echo "Click to close tab" face
  		 (:box nil) display
  		 (image :type svg :file
  			 "/opt/homebrew/Cellar/emacs-plus@30/30.2/share/emacs/30.2/etc/images/symbols/cross_16.svg"
  			 :height (1 . em) :scale 1 :margin 1 :ascent center
  			 :transform-smoothing t))))))
#+end_src

** Minibuffer
Using vertico-posframe, it’s possible to have the minibuffer in the center of the screen. I’m not sure how much I’ll like this functionality, but I’ll test it out for now.
#+begin_src emacs-lisp
  (use-package vertico-posframe
      :after vertico
      :config
      (setq vertico-posframe-handler
          'posframe-poshandler-frame-center)
      (vertico-posframe-mode 1))
#+end_src

* Core Editing
** Project Management
I originally used project.el, but I’ve decided to try projectile instead. I’ll add that now:
#+begin_src emacs-lisp
  (use-package projectile
      :ensure t
      :init
      (setq projectile-project-search-path '("~/Coding"))
      :config
      (projectile-mode +1)
      :bind (:map projectile-mode-map
                ("C-c p" . projectile-command-map)))
#+end_src
** Jumping
I use Avy to quickly jump to any visible text. The function I primarily use here is goto-char-timer, and I’ve dropped that timer all the way down to 0.15 seconds for speed.
+I previously used goto-char-timer, and I’m starting to realize that it’s not the best for me. I always end up typing the whole word, or if not, thinking about how many characters to type. This is suboptimal, so I need a consistent method. Given this, I should just use goto-char or goto-char-2. I’ll start by trying goto-char-2.+
#+begin_src emacs-lisp
  (use-package avy
      :ensure t
      :config
      (setq avy-timeout-seconds 0.15)
      :bind (("M-j" . avy-goto-char)))

#+end_src

Just for visual clarity, I also want to briefly highlight the thing we jump to. In order to do this, let’s define a function for briefly pulsing the current thing:
#+begin_src emacs-lisp
  (defun pulse-symbol-at-point ()
      "Briefly pulse the symbol under the current point."
      (interactive)
      (let* ((bounds (bounds-of-thing-at-point 'symbol))
                (first (car bounds))
                (last (cdr bounds)))
          (pulse-momentary-highlight-region first last)))
#+end_src

+Next, run this function whenever we jump from Avy:+ The new goto-char-2 function breaks this, so I’ll have to fix it later if I decide to stay with goto-char-2.
#+begin_src emacs-lisp
  (require 'avy)

  (advice-add 'avy-goto-char-timer :after #'pulse-symbol-at-point)
#+end_src

I also want this functionality on each jump of an incremental search.
#+begin_src emacs-lisp
  (add-hook 'isearch-mode-end-hook #'pulse-symbol-at-point)
#+end_src

I also want the ability to jump between windows, for which purpose I believe ace-window is the best choice.
#+begin_src emacs-lisp
  (use-package ace-window)
  (bind-key* "M-o" 'ace-window)
#+end_src

** Commenting
I want commenting to work like in most editors. Specifically, I want to run comment-or-uncomment region; I want to run it on the region if it’s active, or the current line if not.
#+begin_src emacs-lisp
  (defun my/comment-uncomment ()
  	"Runs comment-uncomment on the region if active, or the current line if not."
  	(interactive)
      (if (region-active-p)
  		(progn (comment-or-uncomment-region (region-beginning) (region-end)))
  		(progn (push-mark)
  			(beginning-of-line)
  			(push-mark)
  			(end-of-line)
  			(comment-or-uncomment-region (region-beginning) (region-end))
  			(set-mark-command t)
  			(set-mark-command t))))

  ;; (global-set-key (kbd "C-/") 'my/comment-uncomment)
#+end_src

** Multiple Cursors
This one’s pretty straightforward. As a former VSCode user, I like multiple cursors for simultaneously editing different things (and it just looks really cool).
#+begin_src emacs-lisp :tangle no
  (package-install 'multiple-cursors)
  (require 'multiple-cursors)
#+end_src

Note: a list of mc commands can be found [[https://github.com/magnars/multiple-cursors.el?tab=readme-ov-file#command-overview][here]].

I’m not using anything close to the full functionality of this package; for now, I just want to bind C-d and C-S-d to mark and unmark the next instances of the current word.
#+begin_src emacs-lisp :tangle no
  (global-set-key (kbd "C-d") 'mc/mark-next-like-this-word)
  (global-set-key (kbd "C-S-d") 'mc/unmark-next-like-this)
#+end_src

When using this command, the word is selected by default. This leads to some inconvenience, so I’ll disable delete-selection-mode so that it’s possible to type stuff at the end of a word after using this command. We then re-enable it after exiting mc mode. I also make sure delete-selection-mode is enabled to begin with.
#+begin_src emacs-lisp :tangle no
  (delete-selection-mode 1)
  (add-hook 'multiple-cursors-mode-hook (lambda () (delete-selection-mode -1)))
  (add-hook 'multiple-cursors-mode-disabled-hook (lambda () (delete-selection-mode 1)))
#+end_src

By default, return is bound to disable mc mode. I dislike this.
#+begin_src emacs-lisp :tangle no
  (define-key mc/keymap (kbd "<return") nil)
#+end_src

Finally, the c++ mode keymap eats C-d. It would be better practice to bind it to something like C-c d, but I’m more used to C-d, so I’ll try to rebind that. Note: this doesn’t actually work 😥.
#+begin_src emacs-lisp :tangle no
  (with-eval-after-load 'c++-mode
      (define-key c++-mode-map (kbd "C-d") nil))
#+end_src

** Off-Screen Cursor
Emacs traditionally does not allow point to exist "offscreen", which is kinda annoying, so I’ll remedy that with the scroll-restore package.

#+begin_src emacs-lisp
  (use-package scroll-restore)
#+end_src

** Moving Lines
This is a feature from VSCode that I quite like. The idea is to move lines around with M-up and M-down, and also to duplicate lines up and down with M-S-up and M-S-down.

Let’s start with swapping lines up and down:
#+begin_src emacs-lisp
  (defun swap-line-up ()
      "Swap the current line with the one above it, retaining cursor position."
      (interactive)
      (if (/= (line-number-at-pos) 1)
          (let ((col (current-column)) (line (line-number-at-pos)))
              (transpose-lines 1)
              (goto-line (- line 1))
              (move-to-column col)
              )))
  
  (defun swap-line-down ()
      "Swap the current line with the one below it, retaining cursor position."
      (interactive)
      (if (/= (line-number-at-pos) (count-lines (point-min) (point-max)))
          (let ((col (current-column)) (line (line-number-at-pos)))
              (forward-line 1)
              (transpose-lines 1)
              (goto-line (+ line 1))
              (move-to-column col)
              )))
#+end_src

We then bind these to keys:
#+begin_src emacs-lisp
    (global-set-key (kbd "M-<up>") 'swap-line-up)
    (global-set-key (kbd "M-<down>") 'swap-line-down)
#+end_src

Duplicating up is very straightforward:
#+begin_src emacs-lisp
  (global-set-key (kbd "M-S-<up>") 'duplicate-line)  
#+end_src

Finally, duplicating down:
#+begin_src emacs-lisp
  (global-set-key (kbd "M-S-<down>") (lambda ()
                                         (interactive)
                                         (let ((col (current-column)))
                                             (duplicate-line)
                                             (forward-line 1)
                                             (move-to-column col))))
#+end_src
** Visual Line Mode
I want visual line mode enabled in text modes:
#+begin_src emacs-lisp
  (add-hook 'text-mode-hook 'visual-line-mode)
#+end_src
** Snippets
For snippets, particularly in LaTeX and HTML, I’ll use yasnippet:
#+begin_src emacs-lisp
  (use-package yasnippet
  	:hook (prog-mode . yas-minor-mode)
  	:config
  	(yas-reload-all))
  (yas-global-mode 1)
#+end_src
** File Saving
Emacs defaults to adding a newline at the end of the file on saving. I dislike this when editing, even though having one is conventional. At some point, I’ll probably add a function to add the newline, save, and then remove it; for now, though, I’ll just disable the newline.
#+begin_src emacs-lisp
  (setq require-final-newline nil)
  (setq mode-require-final-newline nil)
#+end_src
** Confirmation Functions
The default confirmation function is yes-or-no-p, which is a predicate that prompts for a yes or no input. I wish to replace this with y-or-n-p, which only requires a single keypress.
#+begin_src emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
#+end_src

** Confirm on Exit
I want to ask for confirmation before quitting emacs.
#+begin_src emacs-lisp
  (setq confirm-kill-emacs 'yes-or-no-p)
#+end_src

** Auto Revert
When a buffer is changed on disk, I want those changes to be immediately reflected in the buffer.
#+begin_src emacs-lisp
  (global-auto-revert-mode 1)
#+end_src

** Garbage Collection
I’m not entirely sure what this does, but I’ve heard it highly recommended:
#+begin_src emacs-lisp
  (setq gc-cons-threshold 1000000)
#+end_src

** Backup Files
I don’t want the auto-save or backup files that emacs normally creates.
#+begin_src emacs-lisp
  (setq make-backup-files nil)
  (setq auto-save-default nil)
#+end_src

** IBuffer
I want to replace the default buffer list with the ibuffer list:
#+begin_src emacs-lisp
  (require 'ibuffer)
  (global-set-key (kbd "C-x C-b") 'ibuffer-other-window)
#+end_src

** Better Beginning of Line
One issue with the beginning-of-line command, bound to C-a, is that it jumps over all whitespace, which is really annoying when coding. I will therefore replace it with a new version that jumps to the end of the whitespace, and then if used further toggles between the beginning of the line and the end of the whitespace. The code is taken from [[https://emacsredux.com/blog/2013/05/22/smarter-navigation-to-the-beginning-of-a-line/][here]].

#+begin_src emacs-lisp
  (defun smarter-move-beginning-of-line (arg)
    "Move point back to indentation of beginning of line.

  Move point to the first non-whitespace character on this line.
  If point is already there, move to the beginning of the line.
  Effectively toggle between the first non-whitespace character and
  the beginning of the line.

  If ARG is not nil or 1, move forward ARG - 1 lines first.  If
  point reaches the beginning or end of the buffer, stop there."
    (interactive "^p")
    (setq arg (or arg 1))

    ;; Move lines first
    (when (/= arg 1)
      (let ((line-move-visual nil))
        (forward-line (1- arg))))

    (let ((orig-point (point)))
      (back-to-indentation)
      (when (= orig-point (point))
        (move-beginning-of-line 1))))

  ;; remap C-a to `smarter-move-beginning-of-line'
  ;;(global-set-key [remap move-beginning-of-line]
                 ;; 'smarter-move-beginning-of-line)
#+end_src

* Completions and Search
** Keybinding Completion
I’ll use the which-key package to help with completions for keybindings.
#+begin_src emacs-lisp
  (use-package which-key
      :ensure t
      :config
      (which-key-mode +1))
#+end_src
** Minibuffer Completion
For completion in the minibuffer, I’ll use vertico:
#+begin_src emacs-lisp
  (use-package vertico
      :init
      (vertico-mode)
      :bind (:map vertico-map
      ("C-j" . vertico-next)
      ("C-k" . vertico-previous)))
#+end_src

I also want to hide all commands that aren’t available in the current mode. This snippet comes from the Shane Kennedy blog post I linked previously.
#+begin_src emacs-lisp
  (use-package emacs
      :custom
      (read-extended-command-predicate #'command-completion-default-include-p))
#+end_src

Finally, I’ll use marginalia. This package makes it so that the completion options in the minibuffer also display the docstring for that command.
#+begin_src emacs-lisp
  (use-package marginalia
      :init
      (marginalia-mode))
#+end_src
** In-Buffer Completion
As far as I can tell, there are two primary options for in-buffer completion: company and corfu. Because I’m already using other Minad packages, it seems most logical to go for corfu here. This is a pretty minimal setup. I currently have a map that’s commented out, because I’m still deciding on the best keybindings here.
#+begin_src emacs-lisp
  (use-package corfu
    :custom
    (corfu-auto t)
    (corfu-cycle t) ;; Enable cycling for `corfu-next/previous'
    :hook ((prog-mode . corfu-mode)
  	 (shell-mode . corfu-mode)
  	 (eshell-mode . corfu-mode))
    :bind
    (:map corfu-map
          ;;     ("TAB" . corfu-next)
          ;;     ("C-n" . corfu-next)
          ;;     ([tab] . corfu-next)
          ;;     ("C-p" . corfu-previous)
          ;;     ("S-TAB" . corfu-previous)
          ;;     ([backtab] . corfu-previous)
  	("M-<backspace>" . backward-kill-word)
  	("C-<backspace>" . backward-kill-word)
  	;; ("ESC" . corfu-quit)
  	))
#+end_src

I also want to delay the completion a little bit, instead of it popping up immediately. I have this code set up to add a time delay of 0.2 seconds; however, the corfu documentation states that this can create lag, so I’ve commented it out for now.
#+begin_src emacs-lisp
  (setq corfu-auto-delay 0)
  (setq corfu-auto-prefix 2)
#+end_src
** Fuzzy Matching
I use orderless to give completions fuzzy matching. This particular bit of code is copied directly from the Shane Kennedy blog post.
#+begin_src emacs-lisp
  (use-package orderless
      :custom
      (completion-styles '(orderless basic))
      (completion-category-defaults nil)
      (completion-category-overrides '((file (styles basic partial-completion)))))
#+end_src
** Searching
I’ll use Consult for better searching. When I say "use" I don’t actually mean use, because I haven’t figured it out yet. However, I’ll install it for now.
#+begin_src emacs-lisp :tangle no
(use-package consult
        :hook (completion-list-mode . consult-preview-at-point-mode)
        :custom
        (consult-preview-key nil)
        (consult-narrow-key nil)
        :config
        (consult-customize consult-theme consult-line consult-line-at-point :preview-key '(:debounce 0.2 any))
        )
#+end_src

#+begin_src emacs-lisp
  (use-package consult)
  (use-package consult-projectile
    :after (consult projectile))
#+end_src

I’ll replace some basic keybindings with their equivalent consult commands:

#+begin_src emacs-lisp
  (global-set-key (kbd "C-s") #'consult-line)
  (global-set-key (kbd "C-x b") #'consult-buffer)
  (global-set-key (kbd "C-M-l") #'consult-imenu)
  (global-set-key (kbd "M-y") #'consult-yank-pop)
#+end_src
** Sorting
In order to better sort lists of options, I’ll use prescient.
#+begin_src emacs-lisp
  (use-package prescient
    :config
    (prescient-persist-mode 1))
#+end_src

Integration with vertico:
#+begin_src emacs-lisp
  (use-package vertico-prescient
    :after vertico
    :config
    (setq vertico-prescient-enable-filtering nil)
    (vertico-prescient-mode 1))
#+end_src

Integration with corfu:
#+begin_src emacs-lisp
  (use-package corfu-prescient
    :after corfu
    :config
    (setq corfu-prescient-enable-filtering nil)
    (corfu-prescient-mode 1))
#+end_src

Note that currently, I’m still using orderless for filtering, and just using prescient for the sorting.

* Org Mode
** UI Improvements
I’m using org-modern to improve the ui on org-mode documents. I haven’t customized this much yet, but probably will do so in the future.
#+begin_src emacs-lisp
  (package-install 'org-modern)
  (with-eval-after-load 'org (global-org-modern-mode))
#+end_src

I want org-modern to ignore tables, because it conflicts with valign.

#+begin_src emacs-lisp
  (setq org-modern-table nil)
#+end_src

I also want my documents centered when on a larger screen, so I’ll use Olivetti.
#+begin_src emacs-lisp
  (package-install 'olivetti)
  (setq olivetti-body-width 0.6)
  (add-hook 'org-mode-hook #'olivetti-mode)
#+end_src

Finally, I always want org indent mode on. This indents subsequent headings and just makes it much easier to see what heading I’m under. I’ll also enable visual line mode.
#+begin_src emacs-lisp
  (add-hook 'org-mode-hook 'org-indent-mode)
  (add-hook 'org-mode-hook 'visual-line-mode)
#+end_src
** LaTeX
I use CDLatex to input LaTeX quickly.
#+begin_src emacs-lisp
  (package-install 'cdlatex)
  (require 'cdlatex)
#+end_src

I also have a few custom templates for CDLatex.
#+begin_src emacs-lisp
  (setq cdlatex-command-alist
      '(("lap" "Insert Laplace transform" "\\mathcal L {" cdlatex-lr-pair nil nil t)
           ("ilap" "Insert inverse Laplace transform" "\\mathcal L^{-1} {" cdlatex-lr-pair nil nil t)
           ("lim" "Insert limit" "\\lim_{?}" cdlatex-position-cursor nil nil t)
           ("()" "Insert inline math" "\\(?\\)" cdlatex-position-cursor nil t nil)
  	 ("tt" "Insert \\text{}" "\\text{?}" cdlatex-position-cursor nil nil t)
           ("hb" "Insert \\hbar" "\\hbar" nil nil nil t)
  	 ("bb" "Insert \\mathbb" "\\mathbb " nil nil nil t)))
#+end_src

Similarly, some templates for modifying text:
#+begin_src emacs-lisp
  (setq cdlatex-math-modify-alist
        '((118 "\\vb*" nil t nil nil)))
  ;; 6 items: key, mathcmd, textcmd, type (t if has argument, nil if style), rmdot (for if the dot on i and j should be removed idk), and t if italic correction is required.
#+end_src

Finally, though this is not directly related to org mode, I have a custom command to insert inline math, bound to C-(. It uses CDLatex to move the cursor back to the center of the parentheses.
#+begin_src emacs-lisp
  (defun begin-inline-math ()
      "Begins an inline math environment with \\(\\).  Requires cdlatex."
      (interactive)
      (insert "\\(?\\)")
      (cdlatex-position-cursor))
  (add-hook 'org-cdlatex-mode-hook (lambda ()
                                       (keymap-set org-cdlatex-mode-map "C-(" #'begin-inline-math)))  
#+end_src

Now we need to ensure that CDLatex is enabled in all org mode buffers.
#+begin_src emacs-lisp
  (add-hook 'org-mode-hook #'turn-on-org-cdlatex)
#+end_src

I’ll also use Auctex for some other LaTeX utilities like syntax highlighting.
#+begin_src emacs-lisp
  (package-install 'auctex)
  (setq TeX-auto-save t)
  (setq TeX-parse-self t)
  (setq-default TeX-master nil)
#+end_src

** Encryption
I’ll use GPG and org-crypt to allow for the encryption of specific headings in org mode.
#+begin_src emacs-lisp
  (require 'org-crypt)
  (org-crypt-use-before-save-magic)
  (setq org-crypt-key nil)
#+end_src

I want encryption on the crypt tag:
#+begin_src emacs-lisp
  (setq org-crypt-tag-matcher "crypt")
  (setq org-tags-exclude-from-inheritance '("crypt"))
#+end_src

** Roam
Previous note-taking has been accomplished with text files, and more recently with hierarchical org note files. I’d like to instead use org-roam for notes.
#+begin_src emacs-lisp
  (use-package org-roam
  	:ensure t
  	:custom
  	(org-roam-directory "~/org-roam")
  	:bind (("C-c n l" . org-roam-buffer-toggle)
  			  ("C-c n f" . org-roam-node-find)
  			  ("C-c n i" . org-roam-node-insert)
  			  :map org-roam-dailies-map
  			  ("Y" . org-roam-dailies-capture-yesterday)
  			  ("T" . org-roam-dailies-capture-tomorrow))
  	:bind-keymap
  	("C-c n d" . org-roam-dailies-map)
  	:config
  	(require 'org-roam-dailies)
  	(org-roam-setup))
#+end_src

The org-roam author recommends displaying the org-roam buffer as a separate window like this:
#+begin_src emacs-lisp
  (add-to-list 'display-buffer-alist
  	'("\\*org-roam\\*"
  		 (display-buffer-in-direction)
  		 (direction . right)
  		 (window-width . 0.33)
  		 (window-height . fit-window-to-buffer)))
#+end_src

I’ll want to create some custom capture templates at some point, so I’ll override the templates variable, currently only providing the default template:
#+begin_src emacs-lisp
  (setq org-roam-capture-templates
        '(("d" "default" plain "%?"
    	 :target (file+head "%<%Y%m%d%H%M%S>-${slug}.org"
    			    "#+title: ${title}\n")
    	 :unnarrowed t
  	 :empty-lines 1
  	 )
  	("p" "physics" plain "%?"
    	 :target (file+head "%<%Y%m%d%H%M%S>-${slug}.org"
    			    "#+startup: latexpreview\n#+latex_header: \\usepackage{physics}\n#+filetags: :physics:\n#+title: ${title}")
    	 :unnarrowed t
  	 )
  	("m" "math" plain "%?"
    	 :target (file+head "%<%Y%m%d%H%M%S>-${slug}.org"
    			    "#+startup: latexpreview\n#+filetags: :math:\n#+title: ${title}")
    	 :unnarrowed t
  	 )))
#+end_src

I also want to use file tags to distinguish between subjects:
#+begin_src emacs-lisp
  (setq org-roam-node-display-template
        (concat "${title:*} " (propertize "${tags:10}" 'face 'org-tag)))
#+end_src

** Roam Dailies
All daily roam notes should be stored in the /daily subfolder:
#+begin_src emacs-lisp
  (setq org-roam-dailies-directory "daily/")
#+end_src

I want two capture templates. The first is copied directly from the documentation, and consists solely of a single headline. The second is for journal entries, and is therefore its own node. Journal id is 04086C07-D098-4447-9999-43E974375A32
#+begin_src emacs-lisp
  (setq org-roam-dailies-capture-templates
      '(("d" "default" plain
            "* %?"
            :target (file+head "%<%Y-%m-%d>.org"
                        "#+title: %<%Y-%m-%d>\n")
  		  :empty-lines 1)
  		 ("j" "journal" entry
  			 "* Journal: %^{Title}\n\n%?"
  			 :target (file+head "%<%Y-%m-%d>.org"
  						 "#+title: %<%Y-%m-%d>\n")
  			 :empty-lines 1)
  		 ))
#+end_src
** Roam UI
There’s a package for displaying a graph of all your org-roam nodes. I don’t think it’s that useful, but it looks cool so why not.
#+begin_src emacs-lisp
  (use-package org-roam-ui
      :after org-roam
  	;;         normally we'd recommend hooking orui after org-roam, but since org-roam does not have
  	;;         a hookable mode anymore, you're advised to pick something yourself
  	;;         if you don't care about startup time, use
  	;;  :hook (after-init . org-roam-ui-mode)
      :config
      (setq org-roam-ui-sync-theme t
          org-roam-ui-follow t
          org-roam-ui-update-on-save t
          org-roam-ui-open-on-start t))
#+end_src

In the future, I’d like to prevent it from automatically opening a tab in my browser, and instead display it with an xwidget-webkit.

** Custom Commands
One great thing about org mode is that you can have a large document but hide the majority of it, excepting only what you’re currently working on. However, there’s no good command to do this. I’m therefore adding a shortcut by combining two other commands.
#+begin_src emacs-lisp
  (defun org-fold-all-reveal ()
  	"Cycle global visibility, then reveal."
  	(interactive)
  	(org-shifttab 1)
  	(org-fold-reveal)
  	(message "")
  	)
#+end_src

I want this bound to C-c C-h in org mode.
#+begin_src emacs-lisp
  (define-key org-mode-map (kbd "C-c C-h") #'org-fold-all-reveal)
#+end_src

** Tables
I’m noticing that table alignment fails when using things like previewed latex. I’ll try to fix this with valign.
#+begin_src emacs-lisp
  (use-package valign
  	:hook (org-mode . valign-mode)
  	:config (setq valign-fancy-bar t))
#+end_src

** Babel
In order to use org mode’s excellent Babel feature, I need to include the languages I want to use here:
#+begin_src emacs-lisp
  (org-babel-do-load-languages
  	'org-babel-load-languages '((python . t)))
#+end_src

This fixes python, hopefully, but is system dependent:
#+begin_src emacs-lisp
  (setq org-babel-python-command "/usr/bin/python3")
#+end_src

* Programming
** Language Server Protocol Client
I want to use the built-in eglot for LSP stuff.
#+begin_src emacs-lisp
  (use-package eglot
    :ensure t
    :hook ((python-ts-mode . eglot-ensure)
           (c-ts-mode      . eglot-ensure)
           (c++-ts-mode    . eglot-ensure)
           (js-ts-mode     . eglot-ensure)
           (java-ts-mode   . eglot-ensure))
    :config
    (add-to-list 'eglot-server-programs
                 '(html-mode . ("vscode-html-language-server" "--stdio"))))
#+end_src

** Language Servers
For c++, I want to use clangd. I’m going to assume this is already installed via homebrew on mac:
#+begin_src emacs-lisp
  ;; (if (eq system-type 'darwin)
  ;; 	(setq lsp-clients-clangd-executable "/opt/homebrew/bin/clangd"))
#+end_src

** Web Development
For quick completions, I’ll use emmet-mode:
#+begin_src emacs-lisp
  (use-package emmet-mode
  	:hook (html-mode css-mode web-mode)
  	:config
  	(keymap-set emmet-mode-keymap "TAB" #'emmet-expand-line))
#+end_src

I also want to make mhtml mode inherit the prog-mode stuff:
#+begin_src emacs-lisp
  ;; (add-hook 'mhtml-mode-hook (lambda ()
  ;; 			     (run-hooks 'prog-mode-hook)))
  (derived-mode-add-parents 'mhtml-mode '(prog-mode))
#+end_src

** Syntax Highlighting
I’ll use tree-sitter for completion. It’s included with emacs now, but this config should allow me to set the sources for my languages.
#+begin_src emacs-lisp
  (use-package treesit
    ;; No :ensure t because it's built into Emacs 30
    :ensure nil
    :config
    (setq treesit-language-source-alist
          '((python "https://github.com/tree-sitter/tree-sitter-python")
            (javascript "https://github.com/tree-sitter/tree-sitter-javascript")
            (cpp "https://github.com/tree-sitter/tree-sitter-cpp")
            (c "https://github.com/tree-sitter/tree-sitter-c")
            (java "https://github.com/tree-sitter/tree-sitter-java")
            (css "https://github.com/tree-sitter/tree-sitter-css")
            (html "https://github.com/tree-sitter/tree-sitter-html"))))

  (setq treesit-extra-load-path '("~/.emacs.d/tree-sitter-gdscript/src"))
#+end_src

I also want to remap most programming modes to use their treesit counterparts:
#+begin_src emacs-lisp
  ;; Remap standard modes to Tree-sitter modes
  (setq major-mode-remap-alist
        '((python-mode     . python-ts-mode)
          (c-mode          . c-ts-mode)
          (c++-mode        . c++-ts-mode)
          (js-mode         . js-ts-mode)
  	(javascript-mode . js-ts-mode)
          (java-mode       . java-ts-mode)
          (css-mode        . css-ts-mode)
          (html-mode       . html-ts-mode)
          (typescript-mode . typescript-ts-mode)))
#+end_src

** Highlight Current Line
Emacs has a built-in minor mode to highlight the current line, which I want to be active in all programming modes.

#+begin_src emacs-lisp
  (add-hook 'prog-mode-hook #'hl-line-mode)
#+end_src

** Linting
I’ll use the built-in flymake package for linting. This should require minimal configuration. I will bind some keys to jump between errors.
#+begin_src emacs-lisp
  (use-package flymake
    :bind (("M-n" . flymake-goto-next-error)  ; Move to next error
           ("M-p" . flymake-goto-prev-error)) ; Move to previous error
    :hook (prog-mode . flymake-mode))
#+end_src

** Version Control
For help with version control, I’ll use magit. I currently don’t have this customized at all.
#+begin_src emacs-lisp
  (use-package magit)
#+end_src

I also want to use forge, which is the magit integration with git forges like github and gitlab.
#+begin_src emacs-lisp
  (use-package forge
    :after magit)
#+end_src

** Indentation
I want indentation lines to be displayed, so I’ll use the indent-bars package.
#+begin_src emacs-lisp
  (use-package indent-bars
    :ensure t
    :hook ((prog-mode . indent-bars-mode))
    :config
    (setq 
          indent-bars-prefer-character t

          ;; Show indent guides starting from the first column.
          indent-bars-starting-column 0
          ;; Make indent guides subtle; the default is too distractingly colorful.
          indent-bars-width-frac 0.15  ; make bitmaps thinner
          indent-bars-color-by-depth nil
          indent-bars-color '(font-lock-comment-face :face-bg nil :blend 0.425)
          ;; Don't highlight current level indentation; it's distracting and is
          ;; unnecessary overhead for little benefit.
          indent-bars-highlight-current-depth nil
          ;; The default is `t', which shows indent-bars even on blank lines
          ;; beyond the end of an indented block. Setting it to `nil' will cause
          ;; gaps in the indent guides, which looks odd. `least' is a good
          ;; compromise, and doesn't suffer the scrolling issue.
          indent-bars-display-on-blank-lines 'least))
#+end_src

** Line numbers
I want line numbers when programming. The last two lines here make sure the line number bar takes up a constant amount of space, preventing weird shifts when scrolling.
#+begin_src emacs-lisp
  (add-hook 'prog-mode-hook 'display-line-numbers-mode)
  (setq display-line-numbers-width-start t)
  (setq display-line-numbers-grow-only t)

#+end_src

** Parentheses
I’ve historically just used the built-in electric-pair-mode.
#+begin_src emacs-lisp
  ;; (add-hook 'prog-mode-hook 'electric-pair-local-mode)
#+end_src

However, I’m going to try smartparens instead:
#+begin_src emacs-lisp
  (use-package smartparens
    :ensure smartparens
    :hook (prog-mode text-mode markdown-mode)
    :config
    (require 'smartparens-config))
#+end_src

This does mean that I have to reimplement electric-pair-open-newline-between-pairs, however. This is the function that will be called whenever I hit enter after making a pair:
#+begin_src emacs-lisp
  (defun my/newline-and-indent-handler (&rest _ignored)
    "Vertically split an expression inside of a pair."
    (newline-and-indent)
    (forward-line -1)
    (indent-according-to-mode))
#+end_src

And here’s the binding of that handler:
#+begin_src emacs-lisp
  (require 'smartparens)
  (sp-local-pair 'prog-mode "{" nil :post-handlers '((my/newline-and-indent-handler "RET")))
#+end_src

** Python
Emacs is better than Jupyter notebooks, so I’ve implemented a helper function for Babel that executes all the code in a given session in order. This first function gets the session name for a given code block.
#+begin_src emacs-lisp
  (defun my/org-babel-get-session ()
  "Return the name of the current Babel source block session."
  (interactive)
  (cdr (assoc :session (nth 2 (org-babel-get-src-block-info)))))
#+end_src

This second function is a modified version of org-babel-execute-buffer, which tests each source block against the session name the function is called from.
#+begin_src emacs-lisp
  (defun my/org-babel-execute-session (&optional arg)
    "Execute all source blocks in the buffer, belonging to the current session."
    (interactive)
    (let ((current-session (my/org-babel-get-session)))
      (org-babel-eval-wipe-error-buffer)
      (org-save-outline-visibility t
        (org-babel-map-executables nil
  	(if (and
  	     (my/org-babel-get-session)
  	     (string= current-session (my/org-babel-get-session))
  	     (not (string= (my/org-babel-get-session) "none")))
  	    (if (org-element-type-p
  		 (org-element-context) '(babel-call inline-babel-call))
  		(org-babel-lob-execute-maybe)
                (org-babel-execute-src-block arg))))))
    (org-display-inline-images))
#+end_src

I’m going to want this to be a pretty easy command to execute quickly.
#+begin_src emacs-lisp
  (keymap-set org-babel-map "C-v" 'my/org-babel-execute-session)
#+end_src

** Godot
I’ll add Godot’s emacs package.
#+begin_src emacs-lisp
  (use-package gdscript-mode)
#+end_src

** Authentication
I want to use only one file for keeping secrets and other authentication tokens, authinfo.gpg.
#+begin_src emacs-lisp
  (setq auth-sources "~/.authinfo.gpg")
#+end_src

** Code Folding
I just like to have the ability to fold blocks of code at will. This is accomplished using the hideshow minor mode:
#+begin_src emacs-lisp
  (add-hook 'prog-mode-hook 'hs-minor-mode)
#+end_src

* Projects
** Web Server
I often want to start a server to preview a web project. I’ll use a custom function to do this, using projectile. I’ve bound this to C-c C-p w, which is the projectile prefix + w.
#+begin_src emacs-lisp
  (require 'projectile)
  (defun start-web-server-in-project ()
      "Start a simple Python web server in root directory of current project."
      (interactive)
      (projectile-run-async-shell-command-in-root "python3 -m http.server"))

  (define-key projectile-mode-map (kbd "C-c p w") #'start-web-server-in-project)
#+end_src
** Treemacs
Treemacs is a package which creates a buffer displaying the file structure of the current project.
#+begin_src emacs-lisp
  (use-package treemacs
      :ensure t
      :defer t
      :bind
  	(:map global-map
  		("C-c t" . treemacs)))
#+end_src

I want to use this with projectile, which requires the treemacs-projectile package:
#+begin_src emacs-lisp
  (use-package treemacs-projectile
  	:after (treemacs projectile)
  	:ensure t)
#+end_src

* Writing
** Minor Mode
I want to have a minor mode for writing text in emacs. This minor mode should override much of my customization; I want to use a variable-pitch font, enable Olivetti, and change the color theme to have black text on a white background.
#+begin_src emacs-lisp
  (define-minor-mode writing-mode
  	"Minor mode for writing text in a distraction-free environment."
  	:lighter "Writing"
  	:init-value nil
  	(if writing-mode
  		(progn
  			(if (member "Domine" (font-family-list))
  				(setq-local writing--family "Domine")
  				(setq-local writing--family "Times New Roman"))
  			(setq-local face-remapping-alist
  				`((default
  					  :background "#ffffff"
  					  :foreground "#000000"
  					  :family ,writing--family
  					  :height 140)))
  			;; (setq-local face-remapping-alist
  			;; 	(append face-remapping-alist
  			;; 		 '((mode-line (:height 1))
  			;; 		 (mode-line-inactive (:height 1)))))
  			(olivetti-mode 1)
  			(line-number-mode -1)
  			(setq-local writing--mode-line-format mode-line-format)
  			(setq-local mode-line-format nil)
  			(when (bound-and-true-p centaur-tabs-mode)
  				(centaur-tabs-local-mode)
  				(message "toggled")))
  		(buffer-face-mode -1)
  		(kill-local-variable 'face-remapping-alist)
  		(olivetti-mode -1)
  		(setq-local mode-line-format writing--mode-line-format)))
#+end_src

* Miscellaneous
** Exec Path from Shell
This one has come highly recommended; env variables should be grabbed from the shell.
#+begin_src emacs-lisp
  (use-package exec-path-from-shell
      :config
      (exec-path-from-shell-initialize))
#+end_src
** Splash Screen
This is my custom splash screen. I’ll begin by defining a function for convenience. This inserts some text, centers it in the buffer, and then adds a newline.
#+begin_src emacs-lisp
  (defun center-and-newline (text)
        "Insert the provided TEXT, center and newline."
        (insert text)
        (center-line)
        (insert "\n"))
#+end_src

Next, I’ll have a function for turning a given buffer into the splash screen:
#+begin_src emacs-lisp
  (defun bendomine/create-splash-screen()
  	(read-only-mode -1)
  	(erase-buffer)

  	(set-fill-column (window-body-width nil))

  	(let* (
                (height (- (window-body-height nil) 1))
                (offset 10)
                (vertical-padding (- (/ height 2) offset)))
  		(insert-char ?\n vertical-padding))

  	(center-and-newline "+---------------------------------------------------------+")
  	(center-and-newline "| 8888888888888b     d888       d8888 .d8888b.  .d8888b.  |")
  	(center-and-newline "| 888       8888b   d8888      d88888d88P  Y88bd88P  Y88b |")
  	(center-and-newline "| 888       88888b.d88888     d88P888888    888Y88b.      |")
  	(center-and-newline "| 8888888   888Y88888P888    d88P 888888        \"Y888b.   |")
  	(center-and-newline "| 888       888 Y888P 888   d88P  888888           \"Y88b. |")
  	(center-and-newline "| 888       888  Y8P  888  d88P   888888    888      \"888 |")
  	(center-and-newline "| 888       888   \"   888 d8888888888Y88b  d88PY88b  d88P |")
  	(center-and-newline "| 8888888888888       888d88P     888 \"Y8888P\"  \"Y8888P\"  |")
  	(center-and-newline "+---------------------------------------------------------+")

  	(insert "\n")

  	(center-and-newline "Customized by Ben Domine")
  	(insert "\n\n")

  	(insert-text-button "Open config file" 'action (lambda (_) (config)) 'follow-link t)
  	(center-line) (insert "\n\n")
  	;; (local-set-key (kbd "c") (lambda (_) (config)))

  	(insert-text-button "Create org document" 'action (lambda (_)
                                                            (let ((buffer (generate-new-buffer "New org document")))
                                                                (switch-to-buffer buffer)
                                                                (org-mode))) 'follow-link t)
  	(center-line) (insert "\n\n")
  	(insert-text-button "New journal entry" 'action (lambda (_) (org-roam-dailies-capture-today nil "j")) 'follow-link t)
  	;; (local-set-key (kbd "j") (lambda (_) (org-roam-dailies-capture-today nil "j")))
  	
  	(center-line) (insert "\n")

  	(setq mode-line-format nil)
  	(setq cursor-type nil)
  	(setq horizontal-scroll-bar nil)
  	(setq vertical-scroll-bar nil)

  	(read-only-mode 1)
  	(buffer-disable-undo))
#+end_src

Now I have a function to create a buffer and run the previous command:
#+begin_src emacs-lisp
  (defun bendomine/splash-screen ()
      "Display my custom splash screen."
      (interactive)

      (let ((new-buffer (get-buffer-create "*Splash Screen*")))
          (with-current-buffer new-buffer
              (bendomine/create-splash-screen))

          (switch-to-buffer new-buffer)
          (when (bound-and-true-p centaur-tabs-mode) (if (or centaur-tabs-mode centaur-tabs-local-mode) (centaur-tabs-local-mode)))
          (message "")))
#+end_src

Finally, I’ll display that splash screen after load, with a tiny delay to ensure that the frame resizes first:
#+begin_src emacs-lisp
  (add-hook 'window-setup-hook (lambda ()
                                   (run-at-time "0.3 sec" nil #'bendomine/splash-screen)))
#+end_src

I also want to add some local keybindings to quickly choose menu items.
#+begin_src emacs-lisp

#+end_src

** Preventing Messages on C-scroll
This is kind of stupid, but I sometimes have the C modifier key held down when scrolling, and I don’t want that to be special behavior:
#+begin_src emacs-lisp
  (global-set-key (kbd "C-<wheel-up>") nil)
  (global-set-key (kbd "C-<wheel-down>") nil)
#+end_src

** Emacs Everywhere
I’m really not sure what I think about this, but I’ll try emacs-everywhere and see if I end up using it.
#+begin_src emacs-lisp
  (use-package emacs-everywhere
    :ensure t)
#+end_src

I also need to set a specific server directory:
#+begin_src emacs-lisp :tangle no
  (setq server-socket-dir "~/.emacs.d/server")
#+end_src

** Better Documentation
I’ll use the helpful package to improve help windows.
#+begin_src emacs-lisp
  (use-package helpful
    :ensure t)
#+end_src

* EVIL
** General Setup
I’m gonna try evil.

#+begin_src emacs-lisp
  ;; Enable Evil
  (use-package evil
    :init
    (setq evil-want-integration t) ;; This is optional since it's already set to t by default.
    (setq evil-want-keybinding nil) ;; Required for evil-collection to work properly
    (setq evil-want-C-u-scroll t)   ;; Allow C-u to scroll up like in Vim
    (setq evil-want-C-i-jump t)     ;; Allow C-i to jump forward like in Vim
    :config
    (evil-mode 1))
#+end_src

** Collection
And I guess I have to use evil-collection for it to work with my other packages:

#+begin_src emacs-lisp
  (use-package evil-collection
    :after evil
    :ensure t
    :config
    (evil-collection-init))
#+end_src

** Comments
I’m going to use the evil package for commenting, to see if I prefer it to my normal style.
#+begin_src emacs-lisp
  (use-package evil-commentary
    :config
    (evil-commentary-mode))
#+end_src

** Escape Sequence
Escape to escape makes sense, but I’d like to rebind it to something a little closer to home (literally).
#+begin_src emacs-lisp
  (use-package evil-escape
    :ensure t
    :init
    (setq-default evil-escape-key-sequence "jk")
    (setq-default evil-escape-delay 0.15)
    :config
    (evil-escape-mode 1))
#+end_src

** Visual Line vs Logical Line
I want to move by visual line and not by logical line.
#+begin_src emacs-lisp
  (define-key evil-normal-state-map (kbd "j") 'evil-next-visual-line)
  (define-key evil-normal-state-map (kbd "k") 'evil-previous-visual-line)
  (define-key evil-normal-state-map (kbd "gj") 'evil-next-line)
  (define-key evil-normal-state-map (kbd "gk") 'evil-previous-line)
#+end_src

** Leader Key
I want to use the spacebar as a leader, doom-style. I therefore have a big list of commands here:
#+begin_src emacs-lisp
  (require 'ibuffer)
  (require 'helpful)
  (require 'magit)
  (require 'projectile)
  (use-package general
    :ensure t
    :config
    ;; Tell general to integrate with Evil
    (general-evil-setup t)

    ;; Create a custom definer for your leader keys
    (general-create-definer my-leader-def
  			  :states '(normal visual insert emacs)
  			  :keymaps 'override
  			  :prefix "SPC"
  			  ;; This allows you to use Alt+Space as the leader in insert mode
  			  :non-normal-prefix "M-SPC") 

    ;; Now define your keybindings using your new definer
    (my-leader-def
     "SPC" 'execute-extended-command ;; SPC SPC for M-x
     "."   'find-file
     ","   'switch-to-buffer
     "s"   'save-buffer

     ;; File commands
     "f"   '(:ignore t :which-key "file")
     "ff"  'find-file
     "fs"  'save-buffer

     ;; Buffer commands
     "b"   '(:ignore t :which-key "buffer")
     "bb"  'switch-to-buffer
     "bi"  'ibuffer-other-window
     "bk"  'kill-buffer
     "bd"  'kill-current-buffer

     ;; Help commands
     "h"   '(:ignore t :which-key "describe")
     "hf"  'helpful-callable
     "hv"  'helpful-variable
     "hm"  'describe-mode
     "hk"  'helpful-key

     ;; Window commands
     "w"   '(:ignore t :which-key "window")
     "wc"  'delete-window
     "ww"  'delete-other-windows
     "wr"  'split-window-right
     "wd"  'split-window-below
     "wh"  'evil-window-left
     "wj"  'evil-window-down
     "wk"  'evil-window-up
     "wl"  'evil-window-right

     ;; Quit commands
     "q"   '(:ignore t :which-key "quit")
     "qr"  'restart-emacs
     "qq"  'save-buffers-kill-terminal

     ;; Magit commands
     "g"   '(:ignore t :which-key "magit")
     "gg"  'magit-status

     ;; Projectile commands
     "p"   '(:ignore t :which-key "projectile")
     "pp"  'projectile-switch-project
     "pf"  'projectile-find-file
     "pa"  'projectile-add-known-project

     ;; Tab commands
     "t"   '(:ignore t :which-key "tabs")
     "tt"  'tab-new
     "tc"  'tab-close
     "tr"  'tab-rename
     "tl"  'tab-next
     "th"  'tab-previous
     "t SPC" 'tab-switch))

#+end_src
